[project]
name = "godri"
version = "0.1.0"
description = "Google Drive CLI tool"
authors = [{name = "Sebastien MORAND", email = "sebastien.morand@loreal.com"}]
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.0.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.0.0",
    "google-cloud-translate>=3.0.0",
    "colorlog>=6.0.0",
    "aiofiles>=24.0.0",
    "aiohttp>=3.9.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/godri"]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0"
]